# Generated by Django 4.1.4 on 2023-01-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookdatabase",
            options={"ordering": ["title", "author"]},
        ),
        migrations.RemoveField(
            model_name="bookdatabase",
            name="lexile_score",
        ),
        migrations.AddField(
            model_name="bookdatabase",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookdatabase",
            name="grade_level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
