# Generated by Django 4.1.5 on 2023-01-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_bookdatabase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('lexile_score', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookdatabase',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookdatabase',
            name='condition',
        ),
    ]
